app:
    resource: '@AppBundle/Controller/'
    type: annotation
contact:
    path:     /{_locale}/post
    defaults: { _controller: AppBundle:Post:index }
    requirements:
        _locale: '%app.locales%'